### ISSUE TITLE
set_user_memory_region shouldn't be safe

### ISSUE THREAD

**Issue by joshtriplett** [rust-vmm/kvm#38] opened 2019-05-08 10:55 UTC
This crate allows calling `set_user_memory_region` from safe code, but that function takes a raw pointer and length, and has no way to check that that refers to valid memory.

Shouldn't a safe version of that require passing a memory region type from the vm-memory crate?

**Comment by dgreid** [comment] 2019-05-08 19:04
I think so. crosvm has set_user_memory_region marked as unsafe.

**Comment by andreeaflorescu** [comment] 2019-05-09 06:57
I'll update it to unsafe. Thanks!

**Closed as completed** 2019-06-03 14:49 UTC

**Comment by sameo** [comment] 2019-06-03 16:32
The KVM code will check if the userspace address we pass it to is valid (alignment checks and `access_ok()`). I know we should not rely on an implicit knowledge about the underlying code, but I don't think marking this one as `unsafe` is helping us.
cc @bonzini @alexandruag

**Comment by dgreid** [comment] 2019-06-03 16:47
> The KVM code will check if the userspace address we pass it to is valid (alignment checks and `access_ok()`). I know we should not rely on an implicit knowledge about the underlying code, but I don't think marking this one as `unsafe` is helping us.

The danger isn't in giving an invalid region to the kernel. What if a valid region that overlaps other memory is passed in? I don't think we can trust the kernel to fail when we use this to create an alias that can't be reasoned about by the compiler.  This is unsafe because the caller must make those guarantees, we remove the compiler's ability to do so when the memory is shared with the guest.

**Comment by bonzini** [comment] 2019-06-03 17:12
What @dgreid said, plus the lifetime of the MmapRegion is not guaranteed to be as long as the time that the kernel holds it.

**Comment by andreeaflorescu** [comment] 2019-06-04 08:28
@dgreid @bonzini thanks for the explanation. I was confused about it because I was looking at the [documentation](https://doc.rust-lang.org/book/ch19-01-unsafe-rust.html#unsafe-superpowers) for marking functions as unsafe and it didn't seem like passing raw pointers fits any category described in there. This was the initial reason for marking it as unsafe.

For future reference: are there some guidelines anywhere around when to mark a function as unsafe besides what it already stated in the Rust documentation?

**Comment by bonzini** [comment] 2019-06-04 09:14
@andreeaflorescu As you know, in Rust the unsafe part of pointers is dereferencing it, that is creating a pointer is safe but dereferencing it is not. Now I can see your confusion because usually you have two choices for dereferencing a pointer: either you can ensure that the method that does the dereference is safe, and then you just use an unsafe block, or you mark the method containing the dereference as unsafe.

The problem is that in this case the dereference doesn't happen in Rust, it happens in the kernel, so the two choices have to be changed slightly. If you can ensure that all kernel accesses to the pointer will happen safely, you can use an unsafe block. For example, you could do that by passing `Arc<MmapRegion>` to `set_user_memory_region` and storing the reference until the memory region is removed from the KVM memory map[1]. If you cannot ensure that all kernel accesses to the pointer will happen safely (typically meaning that you have no control over the **lifetime** of the kernel's reference to the pointer), then you have to mark the method unsafe.

[1] I'm not suggesting to do this. In the rust-vmm design, managing reference counts to the `MmapRegion`s would be the task of the `GuestMemory` implementation.

**Comment by bonzini** [comment] 2019-06-04 09:16
This is unfortunately not written anywhere, not even in the [Nomicon's section on FFI](https://doc.rust-lang.org/nomicon/ffi.html). I'll open an issue.

**Comment by andreeaflorescu** [comment] 2019-06-04 12:26
@bonzini @dgreid I created a new PR https://github.com/rust-vmm/kvm-ioctls/pull/46 and added a Safety section to the function documentation. Can you take a look?
